//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAshkhasSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldFatherName { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldEmail { get; set; }
        public string fldMobile { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldDesc { get; set; }
        public string fldSh_Shenasname { get; set; }
        public Nullable<int> fldCodeMahalTavalod { get; set; }
        public Nullable<int> fldCodeMahalSodoor { get; set; }
        public Nullable<bool> fldJensiyat { get; set; }
        public string fldTarikhTavalod { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldCodeEnhesari { get; set; }
        public string Personeli_No { get; set; }
        public int fldPersonalId { get; set; }
        public string fldEmploymentStatusTitle { get; set; }
        public string fldTitel_MaleSazemani { get; set; }
        public string fldNameSatation { get; set; }
        public string TypeEstekhdam { get; set; }
        public string fldMahalTavalod { get; set; }
        public string fldMahaleSodoor { get; set; }
        public string fldNameNahi { get; set; }
        public string fldJensiyatName { get; set; }
        public string fldNezamVazife { get; set; }
        public string fldTaahol { get; set; }
        public string fldRasteName { get; set; }
        public Nullable<short> fldTedadFarzand { get; set; }
        public string fldWorkAddress { get; set; }
        public string fldWorkTell { get; set; }
        public string fldEllatMoafiyat { get; set; }
        public Nullable<short> fldNezamVazifeId { get; set; }
        public Nullable<short> fldTaaholId { get; set; }
        public Nullable<short> fldRasteId { get; set; }
        public Nullable<int> fldEllatMoafiyatId { get; set; }
        public string fldDescPost { get; set; }
        public string fldIsMovazafName { get; set; }
        public Nullable<int> fldTypeEstekhdamid { get; set; }
        public string fldPayeName { get; set; }
        public Nullable<bool> fldEstelam { get; set; }
        public string fldMovazaf { get; set; }
        public string ShoghlAmaliyati { get; set; }
        public string fldCompanyName { get; set; }
        public Nullable<int> fldCompanyId { get; set; }
        public Nullable<int> fldShoghlId { get; set; }
    }
}
