//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectDistictAction_Cartable
    {
        public int fldActionsId { get; set; }
        public string fldName_Actions { get; set; }
        public byte[] fldIconAction { get; set; }
        public Nullable<int> fldCount { get; set; }
    }
}
