//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblShowVersionSelect
    {
        public int fldId { get; set; }
        public int fldNatijeErjaId { get; set; }
        public int fldSharhVersionId { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldSharhVersion { get; set; }
        public string fldFileName { get; set; }
        public string fldPasvand { get; set; }
    }
}
