//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblShahrSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public int fldCountyId { get; set; }
        public string fldLatitude { get; set; }
        public string fldLongitude { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldNameCounty { get; set; }
        public string fldNameState { get; set; }
    }
}
