//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblEventSelect
    {
        public int fldId { get; set; }
        public int fldTransactionTypeId { get; set; }
        public int fldTransactionGroupId { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public bool fldFlag { get; set; }
        public string fldDesc { get; set; }
        public string fldTypeName { get; set; }
        public string fldGroupName { get; set; }
        public string fldNameFlag { get; set; }
    }
}
