//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_TicketForwardHistory
    {
        public int fldId { get; set; }
        public string fldHTML { get; set; }
        public string Matn { get; set; }
        public string fldTarikh { get; set; }
        public string fldSeenDate { get; set; }
        public string fldTitle { get; set; }
        public string fldUserName { get; set; }
        public string fldNameUserSeen { get; set; }
        public string FerestandeName { get; set; }
    }
}
