//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblThemDesktop_UserSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldFileDesktopId { get; set; }
        public byte fldType { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public string fldtypeName { get; set; }
        public byte fldThem { get; set; }
        public string fldThemName { get; set; }
    }
}
