//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblErjaSelect
    {
        public int fldId { get; set; }
        public int fldSharhId { get; set; }
        public int fldErjadahandeId { get; set; }
        public string fldTarikhErja { get; set; }
        public string fldTime { get; set; }
        public bool fldTypeErja { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldTypeErjaName { get; set; }
        public string fldNameErjadahande { get; set; }
        public string fldSharh { get; set; }
        public string fldFileName { get; set; }
        public string fldPasvand { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldCodeEnhesari { get; set; }
    }
}
