//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblRequestRankingSelect
    {
        public int fldId { get; set; }
        public string fldTarikhDarkhast { get; set; }
        public int fldFirstRegisterId { get; set; }
        public int fldHadafIdAllowed { get; set; }
        public byte fldType { get; set; }
        public int fldInputId { get; set; }
        public string fldFullName { get; set; }
        public int fldComanyId { get; set; }
        public string fldNameHadaf { get; set; }
        public string fldRequestTypeName { get; set; }
        public int fldHadafId { get; set; }
        public string fldStatusRequest { get; set; }
        public int fldStatusId { get; set; }
        public Nullable<int> fldEnterCycleId { get; set; }
        public Nullable<int> fldCharkheId { get; set; }
        public string fldCharkheName { get; set; }
        public Nullable<int> fldActionId { get; set; }
        public string fldActionName { get; set; }
        public Nullable<int> fldKartablId { get; set; }
        public string fldNameKartabl { get; set; }
        public string fldNameContract { get; set; }
    }
}
