//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblStatuteFirstPageSelect
    {
        public int fldId { get; set; }
        public int fldCompanyId { get; set; }
        public int fldFileId { get; set; }
        public string fldIP { get; set; }
        public int fldFirstRegisterUser { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
