//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblPersonalInfoSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldOrganId { get; set; }
        public int fldTypeEstekhdamId { get; set; }
        public int fldMahalSazmaniId { get; set; }
        public string fldCodeEnhesari { get; set; }
        public System.DateTime fldDateServer { get; set; }
        public bool fldIsMovazaf { get; set; }
        public string fldTarikh { get; set; }
        public string fldPass { get; set; }
        public Nullable<int> fldSazmaniId { get; set; }
        public int fldStationId { get; set; }
        public int fldShakhsId { get; set; }
        public string fldDesc { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldName_Family { get; set; }
        public string fldFatherName { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldMobile { get; set; }
        public string fldTitel_MaleSazemani { get; set; }
        public string fldStationName { get; set; }
        public string fldIsMovazafName { get; set; }
        public string fldMamoorDepo { get; set; }
        public string fldDescPost { get; set; }
        public int fldIsMovazafId { get; set; }
        public string fldMovazaf { get; set; }
        public string TypeEstekhdam { get; set; }
        public string fldEmploymentStatusTitle { get; set; }
        public int fldDegreeOfEducationId { get; set; }
        public string fldDegreeOfEducationName { get; set; }
        public Nullable<bool> fldTypeSafety { get; set; }
        public string fldTypeSafetyName { get; set; }
        public int fldNahiId { get; set; }
        public string fldPersoneli_No { get; set; }
        public string fldDescType { get; set; }
        public Nullable<int> fldfileId { get; set; }
        public string fldTarikhTavalod { get; set; }
        public string fldSh_Shenasname { get; set; }
        public Nullable<int> fldCodeMahalSodoor { get; set; }
        public Nullable<int> fldCodeMahalTavalod { get; set; }
        public string fldNameMahalSodoor { get; set; }
        public string fldNameMahalTavalod { get; set; }
        public string fldWorkAddress { get; set; }
        public string fldStatusTaahol { get; set; }
        public string fldStatusNazemVazife { get; set; }
        public short fldTedadFarzand { get; set; }
        public string fldJensiyat { get; set; }
        public string fldWorkTell { get; set; }
        public Nullable<short> fldNezamVazifeId { get; set; }
        public Nullable<short> fldTaaholId { get; set; }
        public Nullable<short> fldRasteId { get; set; }
        public string fldEllatMoafiyat { get; set; }
        public string fldNameRaste { get; set; }
        public Nullable<int> fldCompanyid { get; set; }
        public string fldNameCompany { get; set; }
        public bool fldfirstLogin { get; set; }
        public string fldPayeName { get; set; }
        public int fldAnvaPayeId { get; set; }
    }
}
