//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblErrorSelect
    {
        public int fldId { get; set; }
        public string fldMatn { get; set; }
        public System.DateTime fldTarikh { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTarikhShamsi { get; set; }
        public string fldName_Family { get; set; }
        public int fldInputID { get; set; }
        public Nullable<int> fldPrsInputID { get; set; }
    }
}
