//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblActionsSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldFileName { get; set; }
        public byte[] fldFile { get; set; }
        public byte fldNoeGhabelCharkheshId { get; set; }
        public bool fldActive_Deactive { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public string fldTitleGhabelCharkhesh { get; set; }
        public Nullable<int> fldFilePdfId { get; set; }
    }
}
