//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SpecificCartablePermissionTreeSelect
    {
        public int NodeId { get; set; }
        public string NodeTitle { get; set; }
        public int CartablId { get; set; }
        public Nullable<byte> NodeType { get; set; }
        public Nullable<bool> Accessed { get; set; }
    }
}
