//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCh_CompanyProfileSelect
    {
        public int fldId { get; set; }
        public bool fldStatusMsg { get; set; }
        public Nullable<int> fldSenderId { get; set; }
        public string fldMsg { get; set; }
        public string fldSentDate { get; set; }
        public string fldSentTime { get; set; }
        public byte fldTypeMsg { get; set; }
        public int fldFirstRegisterId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldIP { get; set; }
        public string fldSenderName { get; set; }
        public string fldStatusMsgName { get; set; }
        public string fldTypeMsgName { get; set; }
        public string fldSentDate_Time { get; set; }
    }
}
