//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblVagon_MalekSelect
    {
        public int fldId { get; set; }
        public int fldVagonId { get; set; }
        public int fldMalekInfoId { get; set; }
        public Nullable<short> fldTypeMalekiyatId { get; set; }
        public string fldAzTarikh { get; set; }
        public string fldTatarikh { get; set; }
        public int fldInputId { get; set; }
        public string fldTitleMalekiyat { get; set; }
        public string fldNameMalek { get; set; }
    }
}
