//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblRegistrationFirstContract_HaghighiSelect
    {
        public int fldId { get; set; }
        public int fldAshkhasId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldInputId { get; set; }
        public string fldName_Family { get; set; }
        public string fldHeaderTitle { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldMobile { get; set; }
    }
}
