//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectAllContract_Project
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public string fldTarikhContract { get; set; }
        public string fldShomareContract { get; set; }
        public string fldTarikhMovafeghat { get; set; }
        public string fldShomareMovafeghat { get; set; }
        public Nullable<int> fldVagonId { get; set; }
        public int fldInputId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldShomareVagon { get; set; }
        public string fldVaznKhali { get; set; }
        public decimal fldToolVagon { get; set; }
        public string fldTypeVagon { get; set; }
        public string fldNameCompany { get; set; }
        public Nullable<int> fldTypeVagonId { get; set; }
        public byte fldTypeSamane { get; set; }
        public string fldSamaneMarjaId { get; set; }
        public byte fldKarbariVagon { get; set; }
        public string fldKarbariVagonName { get; set; }
        public string fldTypeSamaneName { get; set; }
        public string fldShenaseMeli { get; set; }
        public string fldCodeEghtasadi { get; set; }
        public Nullable<int> fldMalekId { get; set; }
        public Nullable<byte> fldTypeContract { get; set; }
        public Nullable<int> fldDizelId { get; set; }
    }
}
