//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblContactSelect
    {
        public int fldId { get; set; }
        public byte fldTypeContactId { get; set; }
        public string fldValue { get; set; }
        public byte fldType { get; set; }
        public int fldUserId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldTyperName { get; set; }
        public string NameTypeContact { get; set; }
        public byte[] fldfile { get; set; }
        public int fldAshkhasId { get; set; }
        public string fldname { get; set; }
        public string fldfamily { get; set; }
        public string fldCodeMeli { get; set; }
        public Nullable<byte> fldTypeshakhs { get; set; }
    }
}
