//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAnnouncement_TreeSelect
    {
        public int fldId { get; set; }
        public int fldAnn_ManagerId { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldStationId { get; set; }
    }
}
