//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAnnouncementManagerSelect
    {
        public int fldID { get; set; }
        public string fldTitle { get; set; }
        public string fldMatn { get; set; }
        public bool fldStatus { get; set; }
        public string fldDesc { get; set; }
        public string fldTarikhShamsi { get; set; }
        public byte[] fldAttachment { get; set; }
        public string fldStatusName { get; set; }
        public int fldAttachmentId { get; set; }
        public string fldPasvand { get; set; }
        public bool fldSeenMovazaf { get; set; }
        public string fldTree_Hadaf { get; set; }
    }
}
