//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblPermission_ClientSelect
    {
        public int fldId { get; set; }
        public int fldHadafId { get; set; }
        public int fldApp_ClientId { get; set; }
        public string App_Title { get; set; }
    }
}
