//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblSign_StampDigitalSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldFileSignId { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public Nullable<int> fldFirstRegisterId { get; set; }
        public Nullable<int> fldFileStampId { get; set; }
        public int fldInputId { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
