//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblUser_PermissionSelect
    {
        public int fldId { get; set; }
        public int fldUserSelectId { get; set; }
        public int fldAppId { get; set; }
        public bool fldIsAccept { get; set; }
        public string fldDesc { get; set; }
    }
}
