//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblEkhtesasActions_CartableSelect
    {
        public int fldId { get; set; }
        public int fldActionsId { get; set; }
        public int fldCartableId { get; set; }
        public int fldOrder { get; set; }
        public string fldDesc { get; set; }
        public string fldName_Actions { get; set; }
        public string fldName_Kartabl { get; set; }
        public byte[] fldFile { get; set; }
        public byte[] fldIconAction { get; set; }
        public int fldCharkheId { get; set; }
        public string fldNameCharkhe { get; set; }
        public int fldCharkhe_EghdamId { get; set; }
        public string fldStatusName { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public bool fldactive { get; set; }
        public string fldActiveName { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldNameGhabelCharkhesh { get; set; }
    }
}
