//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectVersionInformation
    {
        public int fldId { get; set; }
        public string fldTarikhAnjam { get; set; }
        public string fldNameErjadahande { get; set; }
        public string fldSharhNatije { get; set; }
        public string fldSharhShow { get; set; }
        public string fldTypeErjaName { get; set; }
    }
}
