//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptDizelFirstBarname
    {
        public Nullable<int> fldTrain_NO { get; set; }
        public string fldTrainDate { get; set; }
        public string fldDizel_No { get; set; }
        public string fldWagon_No { get; set; }
        public string fldIsMade12 { get; set; }
        public int MinTarikhBar { get; set; }
        public string fldBarnameId { get; set; }
    }
}
