//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblVersionMostanadatSelect
    {
        public int fldId { get; set; }
        public int fldVersionId { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public int fldSharhMostanadatId { get; set; }
        public Nullable<int> fldTimestamp { get; set; }
        public string fldSharhMostanadat { get; set; }
        public string fldFileName { get; set; }
        public string fldTarikhVersion { get; set; }
        public string fldversion { get; set; }
        public string fldPasvand { get; set; }
    }
}
