//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblOperationSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public bool fldGroup { get; set; }
        public bool fldUsable { get; set; }
        public bool fldeffective { get; set; }
        public string fldEffectiveName { get; set; }
        public string fldDescAction { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldDesc { get; set; }
        public string fldGroupName { get; set; }
        public byte[] fldFile { get; set; }
        public string fldUsableName { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public Nullable<int> fldDataTypeId { get; set; }
        public string fldfileName { get; set; }
        public string fldNameDataType { get; set; }
        public string fldMethodName { get; set; }
        public bool fldSpecificShow { get; set; }
        public string fldSpecificShowName { get; set; }
        public string fldFA_Name { get; set; }
        public string fldNameTable { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public bool fldActive_Deactive { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public bool fldtype { get; set; }
        public string fldTypeName { get; set; }
        public string fldNoeCharkheshId { get; set; }
        public string fldNoeCharkheshName { get; set; }
        public Nullable<bool> fldIsDynamic { get; set; }
    }
}
