//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblContract_DetailDizelSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldDizelId { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldInputId { get; set; }
        public string fldDizel_No { get; set; }
        public string fldTypeVagon { get; set; }
    }
}
