//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTaeedatSelect
    {
        public int fldId { get; set; }
        public byte fldType { get; set; }
        public int fldApp_ClientId { get; set; }
        public int fldFirstContractId { get; set; }
        public int fldTableId { get; set; }
        public int fldInputId { get; set; }
        public int fldDescId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTypeName { get; set; }
        public string fldDesc { get; set; }
        public string fldFaNameTable { get; set; }
        public string fldTarikh { get; set; }
        public Nullable<System.TimeSpan> fldZaman { get; set; }
        public string fldTitleTable { get; set; }
        public Nullable<bool> fldSeen { get; set; }
        public string fldNameUser { get; set; }
    }
}
