//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTicketCategorySelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public bool fldType { get; set; }
        public string fldTypeName { get; set; }
        public string fldDesc { get; set; }
        public Nullable<bool> fldAnswer { get; set; }
        public Nullable<bool> fldSee { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldName { get; set; }
    }
}
