//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTypeVagonSelect
    {
        public int fldId { get; set; }
        public string fldTypeVagon { get; set; }
        public int fldInputId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public Nullable<int> fldCodeIdServer { get; set; }
        public Nullable<byte> fldMehvar { get; set; }
        public string fldTitleVagon { get; set; }
        public Nullable<int> fldOrderId { get; set; }
        public byte fldNoe { get; set; }
        public string flsNoeName { get; set; }
    }
}
