//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblScheduleContractSelect
    {
        public int fldId { get; set; }
        public int fldFirstContractId { get; set; }
        public int fldScheduleTitleId { get; set; }
        public string fldAzTarikh { get; set; }
        public string fldTaTarikh { get; set; }
        public int fldInputId { get; set; }
        public string fldFirstContractTitle { get; set; }
        public string fldTitleSchedule { get; set; }
        public Nullable<int> fldHeaderId { get; set; }
    }
}
