//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblContract_ProjectSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public string fldTarikhContract { get; set; }
        public string fldShomareContract { get; set; }
        public string fldTarikhMovafeghat { get; set; }
        public string fldShomareMovafeghat { get; set; }
        public int fldInputId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public Nullable<int> fldMalekId { get; set; }
        public string fldNameCompany { get; set; }
        public string fldSamaneMarjaId { get; set; }
        public string fldShenaseMeli { get; set; }
        public string fldCodeEghtasadi { get; set; }
        public string fldVagonId { get; set; }
        public Nullable<int> fldTedadVagon { get; set; }
        public Nullable<byte> fldTypeContract { get; set; }
        public bool fldIsAccept { get; set; }
        public string fldIsAcceptName { get; set; }
        public string fldTypecontractName { get; set; }
        public string fldDizelId { get; set; }
        public string fldStationId { get; set; }
        public Nullable<int> fldHoghoghiId { get; set; }
        public Nullable<decimal> fldSaghfSarmayeGozari { get; set; }
    }
}
