//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblItemsDynamicRatingSelect
    {
        public int fldId { get; set; }
        public int fldHadafId { get; set; }
        public int fldDynamicRatingId { get; set; }
        public bool fldIsCopy { get; set; }
        public bool fldElzami { get; set; }
        public int fldInputId { get; set; }
        public string fldCopyName { get; set; }
        public string fldElzamiName { get; set; }
        public string fldTitleHadaf { get; set; }
        public string fldTitleRatingDynamic { get; set; }
        public byte fldGeneralRatingId { get; set; }
        public string fldTitleGeneral { get; set; }
    }
}
