//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptHeaderContract_Dizel
    {
        public string fldShomare_GH { get; set; }
        public string fldTarikh_GH { get; set; }
        public string fldTitle { get; set; }
        public string fldNameCompany { get; set; }
        public Nullable<int> fldLogoId { get; set; }
    }
}
