//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectNextAction_CharkheEghdam
    {
        public int fldId { get; set; }
        public int fldCharkheId { get; set; }
        public int fldEghdamId { get; set; }
        public byte fldOrderId { get; set; }
        public string fldDesc { get; set; }
        public bool fldActive { get; set; }
        public Nullable<int> fldOpertionId_Defulte { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int fldInputId { get; set; }
        public bool fldActive_Deactive { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public Nullable<byte> fldNoeGhabelCharkheshId { get; set; }
        public string fldName { get; set; }
        public string fldNameKartabl { get; set; }
    }
}
