//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTicketPermissionSelect
    {
        public int fldId { get; set; }
        public int fldCategoryId { get; set; }
        public int fldTicketUserId { get; set; }
        public bool fldSee { get; set; }
        public bool fldAnswer { get; set; }
        public string fldDesc { get; set; }
    }
}
