//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCompanyLocationSelect
    {
        public int fldId { get; set; }
        public int fldCompanyId { get; set; }
        public int fldShahrId { get; set; }
        public string fldAddress { get; set; }
        public string fldCodePosti { get; set; }
        public string fldTelphon { get; set; }
        public string fldPishShomare_Tel { get; set; }
        public string fldMobileModir { get; set; }
        public string fldNamabar { get; set; }
        public string fldPishShomare_Namabar { get; set; }
        public string fldAddressWebSite { get; set; }
        public string fldEmail1 { get; set; }
        public string fldEmail2 { get; set; }
        public string fldEmail3 { get; set; }
        public string fldIP { get; set; }
        public int fldFirstRegisterUser { get; set; }
        public System.DateTime fldDate { get; set; }
        public byte StateIdLoc { get; set; }
        public short CountryIdLoc { get; set; }
        public string fldCountryName { get; set; }
        public string fldStateName { get; set; }
        public string fldCityName { get; set; }
        public string fldStatus { get; set; }
    }
}
