//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblItemDynamicPropertiesSelect
    {
        public int fldId { get; set; }
        public int fldTitleDynamicId { get; set; }
        public string fldNameKhasiyat_En { get; set; }
        public string fldNameKhasiyat_Fa { get; set; }
        public byte fldJenseKhasiyat { get; set; }
        public bool fldType { get; set; }
        public int fldInputId { get; set; }
        public string fldJenseKhasiyatName { get; set; }
        public string fldTypeName { get; set; }
        public string fldTitleRatingFA { get; set; }
        public int fldItemsDynamicRatingId { get; set; }
        public string fldStringType { get; set; }
    }
}
