//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptAmalKardKoliMosaferi
    {
        public int fldVagonId { get; set; }
        public string fldMasafatTeyShode { get; set; }
        public string fldMasafat_Nafar { get; set; }
        public int fldTedadBelit { get; set; }
        public string fldShomareVagon { get; set; }
        public Nullable<double> fldMasafat_NafarINT { get; set; }
        public string fldTarikhBahreBardari { get; set; }
    }
}
