//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblRegistrationFirstContractSelect
    {
        public int fldId { get; set; }
        public int fldRequestId { get; set; }
        public string fldTitle { get; set; }
        public int fldTedad { get; set; }
        public int fldTypeVagonId { get; set; }
        public int fldInputId { get; set; }
        public string fldTypeVagonName { get; set; }
        public string fldHadafName { get; set; }
        public int ExistsEnter { get; set; }
        public int fldFirstRegisterId { get; set; }
        public string fldFullName { get; set; }
        public int fldHadafId { get; set; }
        public int fldStatus { get; set; }
        public int ExistsNullFile { get; set; }
    }
}
