//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectScheduleTitleByFirstContract
    {
        public int fldScheduleTitleId { get; set; }
        public string fldTitleSchedule { get; set; }
        public string fldAzTarikh { get; set; }
        public string fldTaTarikh { get; set; }
        public int fldScheduleContractId { get; set; }
        public int fldStatus { get; set; }
    }
}
