//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTimeLimit_UserSelect
    {
        public int fldId { get; set; }
        public int fldAppId { get; set; }
        public short fldTimeLimit { get; set; }
        public int fldUserId { get; set; }
    }
}
