//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblRulesSelect
    {
        public int fldId { get; set; }
        public string fldFormul { get; set; }
        public int fldFormulId { get; set; }
        public string fldDesc { get; set; }
        public string fldTarikhEjra { get; set; }
        public Nullable<int> fldCharkheId { get; set; }
        public string fldNameCharkhe { get; set; }
        public Nullable<bool> fldStatus { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
    }
}
