//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_MinusSaham
    {
        public Nullable<long> TedadSaham { get; set; }
        public Nullable<long> Minus { get; set; }
        public long SumSaham { get; set; }
    }
}
