//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblMalek_VagonInfoSelect
    {
        public int fldId { get; set; }
        public string fldSamaneMarjaId { get; set; }
        public byte fldTypeSamane { get; set; }
        public string fldNameCompany { get; set; }
        public string fldCodeEghtasadi { get; set; }
        public string fldShenaseMeli { get; set; }
        public int fldInputId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTypeSamaneName { get; set; }
        public Nullable<int> fldAshkhasHoghoghiId { get; set; }
        public string fldDateSabt { get; set; }
        public string fldShomareSabt { get; set; }
        public string fldTarikhTasis { get; set; }
        public string fldAddress { get; set; }
        public string fldCodePosti { get; set; }
    }
}
