//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCompanyProfileSelect
    {
        public int fldId { get; set; }
        public string fldNationalCode { get; set; }
        public string fldFullName { get; set; }
        public string fldSh_Sabt { get; set; }
        public string fldDateSabt { get; set; }
        public int fldTypeCompanyId { get; set; }
        public int fldFirstRegisterUser { get; set; }
        public Nullable<bool> fldFinal_Sabt { get; set; }
        public bool fldReceiveReport { get; set; }
        public bool fldISAccept { get; set; }
        public Nullable<int> fldUserAccept { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public string fldNameModirAmel { get; set; }
        public string fldFamilyModirAmel { get; set; }
        public string fldStatus { get; set; }
        public Nullable<int> fldFirstRegisterId { get; set; }
        public string fldNickName { get; set; }
        public Nullable<int> fldCityId { get; set; }
        public string fldDateTasis { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public Nullable<int> fldLogoId { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public byte fldStateId { get; set; }
        public short fldCountryId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldTypeCompanyName { get; set; }
        public string fldCountryName { get; set; }
        public string fldStateName { get; set; }
        public string fldCityName { get; set; }
        public Nullable<int> fldAshkhasHoghoghiId { get; set; }
    }
}
