//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblLimitationTimeSelect
    {
        public int fldId { get; set; }
        public int fldUserLimId { get; set; }
        public string fldRoozHafte { get; set; }
        public string fldAzSaat { get; set; }
        public string fldTaSaat { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldTimestamp { get; set; }
    }
}
