//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblOpertion_ActionSelect
    {
        public int fldId { get; set; }
        public int fldActionId { get; set; }
        public int fldOpertionId { get; set; }
        public string fldDesc { get; set; }
        public string NameOperation { get; set; }
        public bool fldEffective { get; set; }
        public bool fldUsable { get; set; }
        public bool fldGroup { get; set; }
        public byte[] fldFileOperation { get; set; }
        public Nullable<int> fldCharkhe_EghdamId { get; set; }
        public int fldCharkheId { get; set; }
        public bool fldSpecificShow { get; set; }
        public string fldGroupName { get; set; }
        public string fldSpecificShowName { get; set; }
        public string fldUsableName { get; set; }
        public string fldEffectiveName { get; set; }
        public string fldNameDataType { get; set; }
        public string fldDescAction { get; set; }
        public string fldNameTable { get; set; }
        public string fldMethodName { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public bool fldfaal { get; set; }
        public string fldFaalName { get; set; }
        public string fldNameAction_Opertion { get; set; }
    }
}
