//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTaeedMarhaleSelect
    {
        public int fldId { get; set; }
        public string fldTarikh { get; set; }
        public Nullable<int> fldCharkheFirstId { get; set; }
        public Nullable<int> fldEghdamId { get; set; }
        public Nullable<int> fldKartablId { get; set; }
        public string fldNameEghdam { get; set; }
        public string fldNamekartabl { get; set; }
        public Nullable<int> fldEnterCycleId { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldcontractId { get; set; }
        public string fldTitleContract { get; set; }
        public string fldFullName { get; set; }
    }
}
