//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblUserGroupSelect
    {
        public int fldID { get; set; }
        public string fldTitle { get; set; }
        public int fldInputID { get; set; }
        public int fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public byte fldUserType { get; set; }
        public string fldUserType_Name { get; set; }
        public string Name_Family { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
    }
}
