//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTicketSelect
    {
        public int fldId { get; set; }
        public string fldHTML { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTarikh { get; set; }
        public bool fldSeen { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldName { get; set; }
        public string fldSeenDate { get; set; }
        public int fldTicketCategoryId { get; set; }
        public string fldTitle { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public string NameNahi { get; set; }
        public Nullable<int> fldUserSeen { get; set; }
        public Nullable<int> fldSourceForwardId { get; set; }
        public Nullable<int> fldUserForwarded { get; set; }
        public Nullable<int> fldSourceReplyId { get; set; }
        public string fldMatnReply { get; set; }
        public string fldNameUserSeen { get; set; }
        public string fldFerestandeName { get; set; }
        public string Matn { get; set; }
        public Nullable<int> fldInputID { get; set; }
        public Nullable<int> fldFirstRegisterId { get; set; }
    }
}
