//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectVagonForRptBarname
    {
        public int fldId { get; set; }
        public int fldTypeVagonId { get; set; }
        public int fldMalek_InfoId { get; set; }
        public string fldShomareVagon { get; set; }
        public string fldVaznKhali { get; set; }
        public Nullable<decimal> fldToolVagon { get; set; }
        public Nullable<int> fldKarbariVagon { get; set; }
        public int fldInputId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldKarbariVagonName { get; set; }
        public string fldNameCompany { get; set; }
        public string fldCodeEghtasadi { get; set; }
        public string fldTypeVagon { get; set; }
        public Nullable<decimal> fldZarfiyatBargiri { get; set; }
    }
}
