//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblStationFareeFromBarSelect
    {
        public int fldId { get; set; }
        public int fldStationCode { get; set; }
        public string fldName { get; set; }
        public byte fldDifId { get; set; }
        public byte fldDistDif { get; set; }
        public bool fldIsActive { get; set; }
        public int fldId_DistDifTbl { get; set; }
        public int fldStationBarnameId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameStation { get; set; }
        public string fldNameNahi { get; set; }
        public string fldNameStation_Nahi { get; set; }
    }
}
