//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblShareholderSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public Nullable<int> fldCompanyProfileId { get; set; }
        public Nullable<short> fldOrganId { get; set; }
        public long fldTedadSaham { get; set; }
        public string fldTarikhSaham { get; set; }
        public int fldFirstRegisterId { get; set; }
        public int fldInputId { get; set; }
        public string fldTypeName { get; set; }
        public string fldTypeId { get; set; }
        public string fldName { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldOrgan_Company { get; set; }
        public string ShomareSabat { get; set; }
        public string ShenaseMeli { get; set; }
        public string fldNamePersonal { get; set; }
        public string fldFamilyPersonal { get; set; }
        public string fldRequestId { get; set; }
        public int fldRequest_ShareholderId { get; set; }
        public Nullable<decimal> DarsadTedadSaham { get; set; }
        public int fldStatus { get; set; }
    }
}
