//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblUserSelect
    {
        public int fldId { get; set; }
        public string fldUserName { get; set; }
        public string fldPassword { get; set; }
        public bool fldActive_Deactive { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public string fldNamePersonal { get; set; }
        public Nullable<int> fldShakhsId { get; set; }
        public bool fldFirstLogin { get; set; }
        public string fldCodeMeli { get; set; }
        public Nullable<int> fldInputID { get; set; }
        public byte fldUserType { get; set; }
        public string fldUserType_Name { get; set; }
        public string fldLimitationUser { get; set; }
        public string fldLimitationType { get; set; }
        public bool fldType { get; set; }
        public string fldTypeName { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodeEnhesari { get; set; }
        public bool fldSetadi { get; set; }
        public string fldStationId { get; set; }
        public Nullable<int> fldUserIdlog { get; set; }
        public Nullable<int> fldFirstRigesterId { get; set; }
        public Nullable<bool> fldNoeKarbar { get; set; }
        public string fldNameNoeKarbar { get; set; }
    }
}
