//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTitleRatingDynamic_CharkheEghdamSelect
    {
        public int fldId { get; set; }
        public int fldCherkhe_EghdamId { get; set; }
        public int fldTitleRatingDynamicId { get; set; }
        public int fldInput { get; set; }
    }
}
