//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAnvaPayeSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public byte fldType { get; set; }
        public string fldDesc { get; set; }
        public string fldTypeName { get; set; }
        public string fldTitle_Type { get; set; }
        public Nullable<byte> fldOrderId { get; set; }
        public Nullable<byte> fldCodePaye { get; set; }
    }
}
