//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectTimeLine
    {
        public int Id { get; set; }
        public int fldUserID { get; set; }
        public int fldCharkheFirstId { get; set; }
        public int fldEghdamId { get; set; }
        public Nullable<int> fldKartablId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameTable { get; set; }
        public string fldNameAction { get; set; }
        public string fldNameKartable { get; set; }
        public int fldCharkheId { get; set; }
        public string fldNameCharkhe { get; set; }
        public string fldNameKarbar { get; set; }
        public string tarikh { get; set; }
        public string ZAMAN { get; set; }
        public byte[] fileCharkhe { get; set; }
        public string fldNameOperation { get; set; }
        public int fldOpertionId { get; set; }
        public byte[] fldFileopertion { get; set; }
        public byte[] fldFileAction { get; set; }
        public byte[] fldFileKartabl { get; set; }
        public Nullable<int> fldFileIdOpertion { get; set; }
        public string fldMethodName { get; set; }
        public string fldNameCompany { get; set; }
        public string fldTitleContrac { get; set; }
        public int fldAllMinute { get; set; }
        public int fldMinute { get; set; }
        public int fldHour { get; set; }
        public int fldDay { get; set; }
        public int fldorderid { get; set; }
    }
}
