//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFirstRegister_SelectedHadafSelect
    {
        public int fldId { get; set; }
        public int fldFirstRegisterId { get; set; }
        public int fldHadafId { get; set; }
        public int fldInputId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTitleHadaf { get; set; }
    }
}
