//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptKoliBarname
    {
        public string fldShomareVagon { get; set; }
        public string fldSumTonazhBar { get; set; }
        public Nullable<int> fldTedad { get; set; }
        public string fldSumMasafat { get; set; }
        public string fldSumKilometr { get; set; }
        public string fldBarname { get; set; }
        public Nullable<double> fldSumKilometrINT { get; set; }
        public Nullable<double> fldSumTonazhBarINT { get; set; }
        public string fldTarikhBahreBardari { get; set; }
    }
}
