//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblStationSelect
    {
        public Nullable<int> fldNahiId { get; set; }
        public int fldCode { get; set; }
        public string fldName { get; set; }
        public Nullable<bool> fldIsActive { get; set; }
        public Nullable<System.DateTime> fldAddLogDate { get; set; }
        public Nullable<System.DateTime> fldEditLog_Date { get; set; }
        public string fldDesc { get; set; }
        public string fldNameNahi { get; set; }
        public Nullable<byte> fldStationType { get; set; }
        public string fldStationTypeName { get; set; }
        public string fldIsActiveName { get; set; }
        public int fldId { get; set; }
        public Nullable<int> fldNahiSeirId { get; set; }
        public Nullable<short> fldNo { get; set; }
        public Nullable<bool> fldTagend { get; set; }
        public Nullable<int> fldCode_Personal { get; set; }
        public byte fldTypeTahvil { get; set; }
        public string fldTypeTahvilName { get; set; }
        public bool fldExternalStation { get; set; }
        public bool fldIsMarzi { get; set; }
        public bool fldMarziDakheli { get; set; }
        public string fldMarziDakheliName { get; set; }
    }
}
