//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_ListCompanyForExcel
    {
        public string fldId { get; set; }
        public string fldNationalCode { get; set; }
        public string fldEmail { get; set; }
        public string fldEmailCompany { get; set; }
        public string fldMobile { get; set; }
        public string fldMobileModirAmel { get; set; }
        public string fldFullName { get; set; }
        public string fldDateTasis { get; set; }
        public string fldSh_Sabt { get; set; }
        public string fldDateSabt { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public string fldName_Family { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public string CityTitle { get; set; }
        public string StateTitle { get; set; }
        public string fldStatus { get; set; }
        public string fldFinal_Sabt { get; set; }
        public string fldReceiveReport { get; set; }
        public string fldCompanyStatus { get; set; }
        public string NameModirAmel { get; set; }
        public string SentType { get; set; }
        public string fldMahallSabt { get; set; }
        public string fldMahallSherkat { get; set; }
        public string fldTypeCompany { get; set; }
        public string fldNamabar { get; set; }
        public string fldCodePosti { get; set; }
        public string fldTelphon { get; set; }
        public string fldAddress { get; set; }
        public string fldAddressWebSite { get; set; }
        public string fldTedadKolSaham { get; set; }
        public string fldMablaghSaham { get; set; }
        public string fldNickName { get; set; }
        public string fldFatherName { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldFirstRegisterUser { get; set; }
        public string AllowedTitle { get; set; }
        public string fldRequestHadafName { get; set; }
        public string fldRequestTypeName { get; set; }
        public string fldHadafSabtName { get; set; }
    }
}
