//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFormatFileSelect
    {
        public int fldId { get; set; }
        public string fldFormatName { get; set; }
        public string fldPassvand { get; set; }
        public byte[] fldIcon { get; set; }
        public string fldDesc { get; set; }
        public string fldIconName { get; set; }
        public int fldInputId { get; set; }
        public byte[] fldTimeStamp { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> fldSize { get; set; }
    }
}
