//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblUploadFileCompanySelect
    {
        public int fldId { get; set; }
        public byte[] fldFile { get; set; }
        public string fldPassvand { get; set; }
        public decimal fldSize { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldFirstRegisterId { get; set; }
        public string fldCodeFileId { get; set; }
        public string fldFileName { get; set; }
        public Nullable<int> fldInputId { get; set; }
    }
}
