//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblContract_Project_DetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldVagonId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldShomareVagon { get; set; }
        public Nullable<decimal> fldVaznKhali { get; set; }
        public Nullable<decimal> fldToolVagon { get; set; }
        public string fldTypeVagon { get; set; }
        public string fldKarbariVagonName { get; set; }
        public string fldTarikhBahreBardari { get; set; }
    }
}
