//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblHelpSelect
    {
        public int fldId { get; set; }
        public string fldFormName { get; set; }
        public Nullable<int> fldFilePdfId { get; set; }
        public Nullable<int> fldFileVideoId { get; set; }
        public string fldDesc { get; set; }
        public string fldPasvand_Pdf { get; set; }
        public string fldFileName_PDF { get; set; }
        public Nullable<decimal> fldFileSize_PDF { get; set; }
        public string fldPasvand_Video { get; set; }
        public string fldFileName_Video { get; set; }
        public Nullable<decimal> fldFileSize_Video { get; set; }
    }
}
