//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblEnterToCycleSelect
    {
        public int fldId { get; set; }
        public int fldCharkheId { get; set; }
        public string fldDesc { get; set; }
        public string Tarikhvorod { get; set; }
        public string fldNameCharkhe { get; set; }
        public byte[] fldFileCharkhe { get; set; }
        public string fldStatusName { get; set; }
        public string fldResult { get; set; }
        public Nullable<int> fldPID { get; set; }
        public byte fldAnavinGhabelCharkheshId { get; set; }
        public Nullable<int> fldcontractId { get; set; }
        public string fldTitleContract { get; set; }
        public string fldFullName { get; set; }
    }
}
