//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblMosavabatSelect
    {
        public int fldId { get; set; }
        public int fldFileId { get; set; }
        public byte fldTypeContractId { get; set; }
        public string fldTitle { get; set; }
        public int fldInputId { get; set; }
        public string fldTitleType { get; set; }
    }
}
