//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFactorsAffectingValues_DetailSelect
    {
        public int fldId { get; set; }
        public int fldAvamelUpgradeId { get; set; }
        public int fldHeaderId { get; set; }
        public string fldValue { get; set; }
        public string fldDesc { get; set; }
        public string fldName { get; set; }
        public string fldEnglishNameFormul { get; set; }
        public int fldTarikh { get; set; }
        public string fldTitleEducation { get; set; }
        public int fldDegreeEducationId { get; set; }
        public string fldCode { get; set; }
    }
}
