//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAddressSelect
    {
        public int fldId { get; set; }
        public string fldLatitude { get; set; }
        public string fldLongitude { get; set; }
        public int fldShahrId { get; set; }
        public int fldContactId { get; set; }
        public int fldCountyId { get; set; }
        public byte fldStateId { get; set; }
        public string fldSharName { get; set; }
    }
}
