//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFinancialValue_DetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public long fldMablaghReyali { get; set; }
        public long fldMablaghArzi { get; set; }
        public int fldInputId { get; set; }
        public int fldTypeVagonId { get; set; }
        public string fldTypeVagon { get; set; }
    }
}
