//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCompanyProfile_DetailSelect
    {
        public int fldId { get; set; }
        public int fldHeaderId { get; set; }
        public int fldFirstRegisterId { get; set; }
        public string fldNickName { get; set; }
        public int fldCityId { get; set; }
        public string fldDateTasis { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public string fldIP { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldLogoId { get; set; }
        public byte fldStateId { get; set; }
        public short fldCountryId { get; set; }
        public string fldStatus { get; set; }
        public string fldNameModir { get; set; }
        public string CodeMeliModir { get; set; }
        public string fldTarikhTavalodModir { get; set; }
        public string fldFamilyModir { get; set; }
    }
}
