//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblEmailSettingSelect
    {
        public int fldId { get; set; }
        public string fldAddressEmail { get; set; }
        public string fldPassword { get; set; }
        public bool fldSSL { get; set; }
        public string fldRecieveServer { get; set; }
        public int fldRecievePort { get; set; }
        public string fldSendServer { get; set; }
        public int fldSendPort { get; set; }
    }
}
