//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCharkhe_EghdamSelect
    {
        public int fldId { get; set; }
        public int fldCharkheId { get; set; }
        public int fldEghdamId { get; set; }
        public byte fldOrderId { get; set; }
        public string fldDesc { get; set; }
        public string fldNameEghdam { get; set; }
        public string fldNameCharkhe { get; set; }
        public byte[] FileCharkhe { get; set; }
        public byte[] FileAction { get; set; }
        public string fldNameKartabl { get; set; }
        public int fldKartablId { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public string fldStatusName { get; set; }
        public string fldNameAction_Status { get; set; }
        public bool fldActive { get; set; }
        public string fldActiveName { get; set; }
        public int fldOpertionId_Defulte { get; set; }
        public string fldOpertionId_DefulteName { get; set; }
        public string fldNameGhabelCharkhesh { get; set; }
        public byte fldNoeGhabelCharkheshId { get; set; }
        public string ExistsItemDynamic { get; set; }
    }
}
