//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblMalek_CompanyProfileSelect
    {
        public int fldId { get; set; }
        public int fldCompanyProfileId { get; set; }
        public int fldMalekInfoId { get; set; }
        public int fldInputId { get; set; }
        public string fldNameCompany { get; set; }
        public string fldFullName { get; set; }
        public string fldNationalCode { get; set; }
        public string fldCodeEghtasadi { get; set; }
    }
}
