//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblReferralRulesSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldCharkhe_EghdamId { get; set; }
        public Nullable<int> fldOpertion_ActionId { get; set; }
        public Nullable<int> fldNextActionId { get; set; }
        public string fldValue { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public string fldFormul { get; set; }
        public byte fldOrder { get; set; }
        public string fldNameAction { get; set; }
        public string fldNameNextAction { get; set; }
        public string fldNameCharkhe { get; set; }
        public string fldNameOpertion { get; set; }
        public string fldOrderName { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
    }
}
