//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblHtmlViewerSelect
    {
        public int fldId { get; set; }
        public int fldApp_ClientId { get; set; }
        public Nullable<int> fldHadafId { get; set; }
        public string fldMatnHtml { get; set; }
        public string NameTableTitle { get; set; }
        public string HadafName { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
    }
}
