//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblInputInfoSelect
    {
        public int fldId { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public string fldIP { get; set; }
        public string fldMACAddress { get; set; }
        public byte fldLoginType { get; set; }
        public int fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldBrowserType { get; set; }
        public string fldKey { get; set; }
        public byte fldAppType { get; set; }
        public string Name_Family { get; set; }
        public string fldLoginTypeName { get; set; }
        public System.DateTime fldDateTime { get; set; }
        public int fldUserSecondId { get; set; }
        public Nullable<int> fldFirstRigesterId { get; set; }
    }
}
