//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblApplicationPartSelect
    {
        public int fldID { get; set; }
        public string fldTitle { get; set; }
        public Nullable<int> fldPID { get; set; }
        public Nullable<byte> fldUserType { get; set; }
        public Nullable<bool> fldTimeLimit { get; set; }
    }
}
