//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblVersionSelect
    {
        public int fldId { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public string fldVersion { get; set; }
        public bool fldNiyazTestAmniyat { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldNiyazTestAmniyatName { get; set; }
        public int HaveMostanad { get; set; }
    }
}
