//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_ListCompany_First
    {
        public string fldId { get; set; }
        public string fldEmail { get; set; }
        public string fldUserName { get; set; }
        public string fldMobile { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public string fldFlag { get; set; }
        public string fldSms { get; set; }
        public System.DateTime fldDate { get; set; }
        public int fldFirstRegisterUser { get; set; }
        public string fldGroupName { get; set; }
    }
}
