//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblSMSEmailCachSelect
    {
        public Nullable<int> fldID { get; set; }
        public string fldMatn { get; set; }
        public string fldShMobile { get; set; }
        public string fldEmail { get; set; }
        public string fldVazeyat { get; set; }
        public string fldNameShakhs { get; set; }
        public Nullable<bool> fldNoeeShakhs { get; set; }
        public Nullable<bool> fldNoeePayam { get; set; }
        public Nullable<int> fldFirstRegisterID { get; set; }
        public Nullable<int> fldInputID { get; set; }
        public string fldNoeeShakhsName { get; set; }
        public string fldNoeePayamName { get; set; }
        public string fldUserName { get; set; }
        public string fldFullName { get; set; }
        public string fldSendDate { get; set; }
        public string fldEmail_Mobile { get; set; }
        public Nullable<bool> fldDeliver { get; set; }
        public string fldDeliverName { get; set; }
    }
}
