//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFileDesktop_UserSelect
    {
        public int fldId { get; set; }
        public byte[] fldFileDesktop { get; set; }
        public string fldPasvand { get; set; }
        public decimal fldSize { get; set; }
        public string fldFileName { get; set; }
    }
}
