//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptAmalkardMosaferi
    {
        public string fldShomareVagon { get; set; }
        public Nullable<int> fldTrainNumber { get; set; }
        public string fldTarikhHarekat { get; set; }
        public Nullable<short> fldWagonNumber { get; set; }
        public Nullable<short> fldCompartmentNumber { get; set; }
        public Nullable<short> fldSeatNumber { get; set; }
        public Nullable<int> fldTicketNumber { get; set; }
        public string fldSeirStartStation { get; set; }
        public string fldSeirEndStation { get; set; }
        public string fldTotalDistance { get; set; }
        public int fldMosafer { get; set; }
        public Nullable<double> fldTotalDistanceINT { get; set; }
        public string fldTarikhBahreBardari { get; set; }
    }
}
