//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblContanctTypeSelect
    {
        public byte fldId { get; set; }
        public string fldType { get; set; }
        public int fldIconId { get; set; }
        public string fldFormul { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public byte[] fldFile { get; set; }
        public string fldFileName { get; set; }
    }
}
