//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_ApplictionPart_Charkhe
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public Nullable<bool> fldStatus { get; set; }
        public string fldStatusName { get; set; }
    }
}
