//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblItemProperties_ClientSelect
    {
        public int fldId { get; set; }
        public int fldDynamicClientId { get; set; }
        public int fldItemPropertisId { get; set; }
        public string fldMeghdar { get; set; }
        public int fldFirstRegisterId { get; set; }
        public string fldNameKhasiyat_En { get; set; }
        public string fldNameKhasiyat_Fa { get; set; }
        public byte fldJenseKhasiyat { get; set; }
    }
}
