//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectUserByUserIdTicket
    {
        public int fldId { get; set; }
        public string fldUserName { get; set; }
        public string fldPassword { get; set; }
        public bool fldActive_Deactive { get; set; }
        public bool fldFirstLogin { get; set; }
        public int fldShakhsId { get; set; }
        public int fldInputID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public byte fldUserType { get; set; }
        public string fldStationId { get; set; }
        public int fldUserId { get; set; }
        public string fldActive_DeactiveName { get; set; }
        public string fldNamePersonal { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldFatherName { get; set; }
        public string fldMobile { get; set; }
        public string fldCodeEnhesari { get; set; }
        public string fldUserType_Name { get; set; }
    }
}
