//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblRegistrationFirstContract_HoghoghiSelect
    {
        public int fldId { get; set; }
        public int fldAshkhasHoghoghiId { get; set; }
        public int fldHeaderId { get; set; }
        public string fldTarikhSanad { get; set; }
        public short fldTedadVagon { get; set; }
        public long fldArzeshRiyali { get; set; }
        public long fldArzeshDolari { get; set; }
        public Nullable<int> fldSanadFileId { get; set; }
        public Nullable<int> fldDaftarcheFileId { get; set; }
        public int fldInputId { get; set; }
        public string fldNameHoghoghi { get; set; }
        public string fldHeaderTitle { get; set; }
        public string fldDolari { get; set; }
        public string fldRiyali { get; set; }
    }
}
