//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_SelectDistictOperation_Action
    {
        public int fldOpertionId { get; set; }
        public string NameOperation { get; set; }
        public bool fldEffective { get; set; }
        public bool fldGroup { get; set; }
        public byte[] fldFileOperation { get; set; }
        public string fldDescAction { get; set; }
        public string fldMethodName { get; set; }
        public Nullable<bool> fldIsDynamic { get; set; }
    }
}
