//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblItemDynamic_ClientSelect
    {
        public int fldId { get; set; }
        public int fldFileId { get; set; }
        public int fldItemDynamicId { get; set; }
        public int fldFirstRegisterId { get; set; }
        public int fldInputId { get; set; }
        public int fldidTitleRatingDynamic { get; set; }
        public string fldCodeFileId { get; set; }
        public int fldStatus { get; set; }
    }
}
