//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblNameTablesSelect
    {
        public int fldId { get; set; }
        public string fldEnNameTables { get; set; }
        public int fldSystemIdTables { get; set; }
        public string fldFaName { get; set; }
    }
}
