//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblEventTablesSelect
    {
        public int fldId { get; set; }
        public int fldNameTablesId { get; set; }
        public int fldEventTypeId { get; set; }
        public Nullable<int> fldFormulId { get; set; }
        public bool fldFlag { get; set; }
        public string fldNameType { get; set; }
        public string fldFaName { get; set; }
        public string fldEnNameTables { get; set; }
        public string fldNameFlag { get; set; }
    }
}
