//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptBarname_Info
    {
        public string fldTarikhGhrardad { get; set; }
        public string fldShomareGharadad { get; set; }
        public string fldNoVagon { get; set; }
        public string fldZarfiyatVagon { get; set; }
        public string fldTedadVagon { get; set; }
        public string NameMalek { get; set; }
        public string TarikhBahrebardari { get; set; }
        public Nullable<int> fldLogoid { get; set; }
    }
}
