//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblProgressSelect
    {
        public int id { get; set; }
        public string Title { get; set; }
        public decimal darsad { get; set; }
        public int inputId { get; set; }
    }
}
