//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblComputationFormulaSelect
    {
        public int fldId { get; set; }
        public string fldFormul { get; set; }
        public string fldLibrary { get; set; }
        public string fldDesc { get; set; }
        public byte[] fldCompiledCode { get; set; }
    }
}
