//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblFirstRegisterSelect
    {
        public int fldId { get; set; }
        public string fldEmail { get; set; }
        public string fldUserName { get; set; }
        public string fldMobile { get; set; }
        public string fldPassword { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodeTaeed { get; set; }
        public bool fldFlag { get; set; }
        public bool fldFirstLogin { get; set; }
        public string fldStatus { get; set; }
        public Nullable<int> fldAshkhasId { get; set; }
        public string fldName_Family { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public string fldNameCompany { get; set; }
        public string fldNameModir { get; set; }
        public string fldShenaseMeli { get; set; }
        public string fldSh_Sabt { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldTarikhTavalod { get; set; }
        public Nullable<bool> fldEstelam { get; set; }
        public string fldSelectedHadaf { get; set; }
        public string fldSelectedHadafName { get; set; }
    }
}
