//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblCharkheSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> fldtimeStamp { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldFileName { get; set; }
        public byte[] fldFile { get; set; }
        public Nullable<bool> fldStatus { get; set; }
        public string fldStatusName { get; set; }
        public byte fldNoeGhebelCharkheshId { get; set; }
        public int fldDefulteOpertionId { get; set; }
        public string fldNameOpertion { get; set; }
        public string fldAnvaGhabelCharkheshName { get; set; }
        public Nullable<bool> fldTypeVorood { get; set; }
        public string fldTypeVoroodName { get; set; }
        public Nullable<int> fldHelpId { get; set; }
        public Nullable<int> fldFilePdfId { get; set; }
        public Nullable<int> fldFileVideoId { get; set; }
        public int ExistsEnter { get; set; }
    }
}
