//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblVersion_SeenSelect
    {
        public int fldId { get; set; }
        public int fldUserId { get; set; }
        public bool fldSeen { get; set; }
        public string fldTarikh { get; set; }
        public int fldVersionId { get; set; }
    }
}
