//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblNatijeErjaSelect
    {
        public int fldId { get; set; }
        public int fldErjaId { get; set; }
        public int fldSharhId { get; set; }
        public string fldTarikhAnjam { get; set; }
        public string fldTime { get; set; }
        public bool fldNatije { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldNatijeName { get; set; }
        public string fldSharh { get; set; }
        public string fldNameErjaDahande { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldsharhVersion { get; set; }
    }
}
