//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_UserLogSelect
    {
        public string fldGroupName { get; set; }
        public string fldTypeName { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldCodeEnhesari { get; set; }
        public string fldFaName { get; set; }
        public string fldJsonParametr { get; set; }
        public Nullable<int> fldNameTablesId { get; set; }
        public byte[] fldRowId { get; set; }
        public string fldStatusName { get; set; }
        public Nullable<bool> fldStatus { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public int fldId { get; set; }
        public string fldMACAddress { get; set; }
        public string fldIP { get; set; }
    }
}
