//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblAshkhasHoghooghiSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public string fldNationalCode { get; set; }
        public Nullable<int> fldFileId { get; set; }
        public string fldTarikhTasis { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public string fldDateSabt { get; set; }
        public string fldShomareSabt { get; set; }
        public string fldCodePosti { get; set; }
        public string fldAddress { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public Nullable<bool> fldFinal_Sabt { get; set; }
    }
}
