//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_GetName_applicationpart
    {
        public int fldId { get; set; }
        public string FullName { get; set; }
        public string NameEdare { get; set; }
        public string NameDastresi { get; set; }
        public string fldUserGroupName { get; set; }
    }
}
