//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblDizelSelect
    {
        public int fldId { get; set; }
        public string fldDizel_No { get; set; }
        public int fldTypeDizelId { get; set; }
        public string fldTypeVagon { get; set; }
        public string fldNameCompany { get; set; }
        public string fldCodeEghtasadi { get; set; }
        public int fldMalek_InfoId { get; set; }
    }
}
