//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblTitleRatingDynamicSelect
    {
        public int fldId { get; set; }
        public string fldTitleFA { get; set; }
        public string fldTitleEN { get; set; }
        public byte fldGeneralRatingId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
        public int fldInputId { get; set; }
        public string fldTitleGeneral { get; set; }
        public string fldTitleEN_FA { get; set; }
        public Nullable<int> fldFormatFileId { get; set; }
        public string fldFormatName { get; set; }
        public string fldPassvand { get; set; }
    }
}
