//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_RptBarname
    {
        public int fldRadif { get; set; }
        public string fldShomareVagon { get; set; }
        public string fldShmareBarname { get; set; }
        public string fldTarikhBarname { get; set; }
        public string fldSeri { get; set; }
        public string fldNameMabda { get; set; }
        public string fldNameMaghsad { get; set; }
        public string fldNoeBar { get; set; }
        public string fldMasaft { get; set; }
        public string fldVaznMahsob { get; set; }
        public string fldVaznVagheii { get; set; }
        public string fldTonKilometr { get; set; }
        public int fldMalek_InfoId { get; set; }
        public Nullable<double> fldVaznVagheiiINT { get; set; }
        public Nullable<double> fldTonKilometrINT { get; set; }
        public string fldTarikhBahreBardari { get; set; }
    }
}
