//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_GetDate
    {
        public System.DateTime fldDateTime { get; set; }
        public string fldTarikh { get; set; }
        public string fldTime { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
    }
}
