//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblHadafGroupNameSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public int fldInputId { get; set; }
        public Nullable<int> fldTimeStamp { get; set; }
    }
}
