//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblApplicationPart_ClientSelect
    {
        public int fldId { get; set; }
        public string fldTitle { get; set; }
        public Nullable<int> fldPId { get; set; }
        public byte fldTypeNamayesh { get; set; }
        public string fldNameTabe { get; set; }
        public byte fldTypeCopy { get; set; }
        public string fldTypeCopyName { get; set; }
    }
}
