//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiSam.Models
{
    using System;
    
    public partial class prs_tblSafDownloadSelect
    {
        public long fldId { get; set; }
        public string fldNameFunc { get; set; }
        public Nullable<int> fldsal { get; set; }
        public Nullable<int> fldTasal { get; set; }
        public string fldMalekId { get; set; }
        public string fldContractId { get; set; }
        public string fldShVagon { get; set; }
        public string fldAzVagon { get; set; }
        public string fldTaVagon { get; set; }
        public string fldTypeVagon { get; set; }
        public Nullable<int> fldState { get; set; }
        public Nullable<bool> fldJozeeM { get; set; }
        public Nullable<bool> fldKoliM { get; set; }
        public Nullable<bool> fldJozeeF { get; set; }
        public Nullable<bool> fldKoliF { get; set; }
        public Nullable<bool> fldJozeeY { get; set; }
        public Nullable<bool> fldKoliY { get; set; }
        public Nullable<byte> fldStatus { get; set; }
        public Nullable<System.DateTime> flddate { get; set; }
        public string fldStatusName { get; set; }
    }
}
