//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RaisamWindowsService.SejamService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SejamServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SejamService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoveTranDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallWebServiceRajaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SejamService() {
            this.Url = global::RaisamWindowsService.Properties.Settings.Default.RaisamWindowsService_SejamService_SejamService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestServiceCompletedEventHandler TestServiceCompleted;
        
        /// <remarks/>
        public event GetMoveTranDetailsCompletedEventHandler GetMoveTranDetailsCompleted;
        
        /// <remarks/>
        public event CallWebServiceRajaCompletedEventHandler CallWebServiceRajaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestService(string username, string password) {
            object[] results = this.Invoke("TestService", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestServiceAsync(string username, string password) {
            this.TestServiceAsync(username, password, null);
        }
        
        /// <remarks/>
        public void TestServiceAsync(string username, string password, object userState) {
            if ((this.TestServiceOperationCompleted == null)) {
                this.TestServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestServiceOperationCompleted);
            }
            this.InvokeAsync("TestService", new object[] {
                        username,
                        password}, this.TestServiceOperationCompleted, userState);
        }
        
        private void OnTestServiceOperationCompleted(object arg) {
            if ((this.TestServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestServiceCompleted(this, new TestServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMoveTranDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MoveTranDetails GetMoveTranDetails(string FromDate, string ToDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> MoveTranId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> CompanyId) {
            object[] results = this.Invoke("GetMoveTranDetails", new object[] {
                        FromDate,
                        ToDate,
                        MoveTranId,
                        CompanyId});
            return ((MoveTranDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoveTranDetailsAsync(string FromDate, string ToDate, System.Nullable<int> MoveTranId, System.Nullable<int> CompanyId) {
            this.GetMoveTranDetailsAsync(FromDate, ToDate, MoveTranId, CompanyId, null);
        }
        
        /// <remarks/>
        public void GetMoveTranDetailsAsync(string FromDate, string ToDate, System.Nullable<int> MoveTranId, System.Nullable<int> CompanyId, object userState) {
            if ((this.GetMoveTranDetailsOperationCompleted == null)) {
                this.GetMoveTranDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoveTranDetailsOperationCompleted);
            }
            this.InvokeAsync("GetMoveTranDetails", new object[] {
                        FromDate,
                        ToDate,
                        MoveTranId,
                        CompanyId}, this.GetMoveTranDetailsOperationCompleted, userState);
        }
        
        private void OnGetMoveTranDetailsOperationCompleted(object arg) {
            if ((this.GetMoveTranDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoveTranDetailsCompleted(this, new GetMoveTranDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CallWebServiceRaja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CallWebServiceRaja() {
            this.Invoke("CallWebServiceRaja", new object[0]);
        }
        
        /// <remarks/>
        public void CallWebServiceRajaAsync() {
            this.CallWebServiceRajaAsync(null);
        }
        
        /// <remarks/>
        public void CallWebServiceRajaAsync(object userState) {
            if ((this.CallWebServiceRajaOperationCompleted == null)) {
                this.CallWebServiceRajaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallWebServiceRajaOperationCompleted);
            }
            this.InvokeAsync("CallWebServiceRaja", new object[0], this.CallWebServiceRajaOperationCompleted, userState);
        }
        
        private void OnCallWebServiceRajaOperationCompleted(object arg) {
            if ((this.CallWebServiceRajaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallWebServiceRajaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveTranDetails {
        
        private Data[] dataField;
        
        private bool isSuccessField;
        
        private int statusCodeField;
        
        private string messageField;
        
        private int errField;
        
        private string msgField;
        
        /// <remarks/>
        public Data[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int Err {
            get {
                return this.errField;
            }
            set {
                this.errField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Data {
        
        private int moveTranIdField;
        
        private string companyField;
        
        private string tranCompanyField;
        
        private int tranNoField;
        
        private string moveDateField;
        
        private string moveTimeField;
        
        private string sourceStationField;
        
        private string targetStationField;
        
        private int pelakNoField;
        
        private int salonNoField;
        
        private string wagonRatingField;
        
        /// <remarks/>
        public int MoveTranId {
            get {
                return this.moveTranIdField;
            }
            set {
                this.moveTranIdField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string TranCompany {
            get {
                return this.tranCompanyField;
            }
            set {
                this.tranCompanyField = value;
            }
        }
        
        /// <remarks/>
        public int TranNo {
            get {
                return this.tranNoField;
            }
            set {
                this.tranNoField = value;
            }
        }
        
        /// <remarks/>
        public string MoveDate {
            get {
                return this.moveDateField;
            }
            set {
                this.moveDateField = value;
            }
        }
        
        /// <remarks/>
        public string MoveTime {
            get {
                return this.moveTimeField;
            }
            set {
                this.moveTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceStation {
            get {
                return this.sourceStationField;
            }
            set {
                this.sourceStationField = value;
            }
        }
        
        /// <remarks/>
        public string TargetStation {
            get {
                return this.targetStationField;
            }
            set {
                this.targetStationField = value;
            }
        }
        
        /// <remarks/>
        public int PelakNo {
            get {
                return this.pelakNoField;
            }
            set {
                this.pelakNoField = value;
            }
        }
        
        /// <remarks/>
        public int SalonNo {
            get {
                return this.salonNoField;
            }
            set {
                this.salonNoField = value;
            }
        }
        
        /// <remarks/>
        public string WagonRating {
            get {
                return this.wagonRatingField;
            }
            set {
                this.wagonRatingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TestServiceCompletedEventHandler(object sender, TestServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMoveTranDetailsCompletedEventHandler(object sender, GetMoveTranDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoveTranDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoveTranDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MoveTranDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MoveTranDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CallWebServiceRajaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591