//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaisamWindowsService
{
    using System;
    
    public partial class prs_tblSMSSettingSelect
    {
        public int fldId { get; set; }
        public string fldUserName { get; set; }
        public string fldPassword { get; set; }
        public string fldShomareKhat { get; set; }
        public Nullable<int> fldTimestamp { get; set; }
    }
}
