//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaisamWindowsService
{
    using System;
    
    public partial class prs_tblSafSMSSelect
    {
        public int fldId { get; set; }
        public string fldMatn { get; set; }
        public byte fldStatus { get; set; }
        public int fldAshkhasId { get; set; }
        public int fldCherkheFirstEghdamId { get; set; }
        public System.DateTime fldDateInsert { get; set; }
        public Nullable<System.DateTime> fldDateErsal { get; set; }
        public int fldInputId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldMobile { get; set; }
    }
}
